
export const types = {
	LOG_IN: "auth/LOG_IN",
	SIGN_UP: 'auth/SIGN_UP',
	LOG_OUT: 'auth/LOG_OUT',
	SIGN_UP_ERROR: 'auth/SIGN_UP_ERROR',
	USER_SUCCESS: 'auth/USER_SUCCESS',
	LOG_IN_ERROR: 'auth/LOG_IN_ERROR',
	USER_REQUEST: 'auth/USER_REQUEST',
	SELECT_PERSON_MALE: 'auth/SELECT_PERSON_MALE',
	SELECT_PERSON_FEMALE: 'auth/SELECT_PERSON_FEMALE',
}